    <html>
    <body>
    <h1>Example</h1>
    <?php if (count($this->paginator)): ?>
    <ul>
    <?php foreach ($this->paginator as $item): ?>
      <li><?php echo $item; ?></li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
     
    <?php echo $this->paginationControl($this->paginator,
                                        'Sliding',
                                        'my_pagination_control.phtml'); ?>
    </body>
    </html>