<div id ="navigation-left" >
						<ul>
						<li>	<a  href= "<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
  						 Home</a></li>
						<li><a  href= "<?php 
		echo $this->url(array('controller'=>'index','action'=>'register'));
		  ?>" >Register</a>
		</li>
						<li><a  href= "<?php 
		echo $this->url(array('controller'=>'index','action'=>'login'));
		  ?>" >Login</a></li>
						</ul>
						  </div>

		   <div id ="navigation-right" >
					
						  </div>